---
services:
  unit3d:
    image: seetwoarrr/unit3d:latest
    networks:
      - unit3d
    build:
      context: ./unit3d
      dockerfile: Dockerfile
      args:
        - "PHP_FPM_VERSION=${php_fpm_version}"
        - "UNIT3D_VERSION=${unit3d_version}"
        - "FPM_HEALTHCHECK_VERSION=${fpm_healthcheck_version}"
  proxy:
    image: nginx:mainline-alpine
    ports:
      - "${proxy_listen_address}:80"
    volumes:
      - ./unit3d.conf:/etc/nginx/conf.d/default.conf
    networks:
      - unit3d

networks:
  unit3d: